<?php

/**
 * @file
 */

/**
 * Implements hook_block_info().
 */
function dart_weather_block_info() {
  $blocks['dart_weather'] = array(
    'info' => t('Dart Weather'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
    'region' => 'Content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'node/*',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * @return  block data
 */
function dart_weather_block_view($delta = '') {
  switch ($delta) {
    case 'dart_weather':
      $block['subject'] = t('Get Today&#8217;s Weather');
      if (TRUE == user_is_logged_in()) {
        $block['content'] = dart_weather_contents();
      }
      else {
        $block['content'] = 'You must be logged in to view weather.';
      }
  }
  return $block;
}

/**
 * Custom content function.
 *
 * Returns html for the block.
 *
 * @return html
 */
function jeff_module_contents() {
  $content = "<div class='weather form-inline'>";
  $content .= '<input title="Enter your ZIP code." id="zipCode" name="weatherZIP" value="" size="25" maxlength="5" class="form-text" type="text" placeholder="ZIP Code">';
  $content .= '<input id="getWeatherButton" name="op" value="Get" class="form-submit" type="submit">';
  $content .= "</div>";
  $content .= "<div id='js_weatherResults'><span id='js_weatherResultsTitle'></span><span id='js_weatherResultsTemp'></span><span id='js_weatherResultsText'></span><span id='js_weatherResultsLink'></span></div>";
  return $content;
}
