<?php

/**
 * @file
 * Create the Dart Weather module.
 */

/**
 * Implements hook_block_info().
 *
 * @return associative array
 */
function dart_weather_block_info() {
  $blocks['dart_weather'] = array(
    'info' => t('Dart Weather'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
    'region' => 'Content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'node/*',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * @return array    Contents and Subject.
 */
function dart_weather_block_view($delta = '') {
  switch ($delta) {
    case 'dart_weather':
      $block['subject'] = t('Get Today&#8217;s Weather');
      if (TRUE == user_is_logged_in()) {
        $block['content'] = dart_weather_contents();
      }
      else {
        $block['content'] = 'You must be logged in to view weather.';
      }
  }
  return $block;
}

/**
 * Build the weather block element structure.
 *
 * @return html
 */
function dart_weather_contents() {
  $content = <<<EOT
  <div class='weather form-inline'>
    <input title="Enter your ZIP code." id="zipCode" name="weatherZIP" value="" size="25" maxlength="5" class="form-text" type="text" placeholder="ZIP Code" onkeyup="this.value=this.value.replace(/[^\d]/,'')">
    <input id="getWeatherButton" name="op" value="Get" class="form-submit" type="submit">
  </div>
  <div id='js_weatherResults'>
    <span id='js_weatherResultsTitle'></span>
    <span id='js_weatherResultsTemp'></span>
    <span id='js_weatherResultsText'></span>
    <span id='js_weatherResultsLink'></span>
  </div>
EOT;
  return $content;
}
